trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Mango(40ef2aec-7a53-4376-ba68-76b93cbdbfdb)'
    subscriptionId: '40ef2aec-7a53-4376-ba68-76b93cbdbfdb'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'East US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/pmithbawkar/Azurepipelinerepo/main/azuredeploy.json'
    overrideParameters: '-projectName pipeline1'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

